spring:
  cloud:
    gateway:
      routes:
        - id: news-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/news/**
          filters:
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
        - id: payments-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/payments/**
        - id: membership-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/membership/**
      default-filters:
        - JwtAuthFilter
  front:
    url: http://localhost:3000

  webflux:
    base-path: /

server:
  port: 8070

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.reactive: DEBUG
    se.sowl.yesterdaygateway: DEBUG

jwt:
  secret:
